---
title: "Can widespread gender role inversion buck gendered social norms?"
author: Matt Turner
date: 4 June 2025
bibliography: 
  - /Users/mt/workspace/Writing/library.bib
format:
  html:
    toc: true
    include-in-header: header.html
    theme: 
      light:
        - theme-light.scss
        - styles.scss
      dark:
        - darkly 
        - theme-dark.scss
        - styles.scss
    fontsize: 0.9em
    linestretch: 1.2
editor: 
  markdown: 
    wrap: 80
---

# Introduction

In diverse sustainability contexts, women have proven more trustworthy stewards
than their male partners. For example, in microfinance programs have been
observed to have greater effects on well-being for women compared to men
[@Karlan2011]. In another example, residential solar subsidies given to men in
Papua New Guinea were reported to be spent more on "pigs, prostitutes, and poker
chips" instead of solar panels [@Sovacool2011].

It seems women-led interventions and institutions to support sustainability.
However, there exists a persistent social norm against women leaders and
achiever, and against men who follow women, across social contexts that can't be
supported, yet persists [@OConnor2019Origins] and is even worse for non-white or
transgender women due to intersectional disadvantage [@OConnor2019c].

Why do women continue to be [shouldered out of
leadership](https://www.soroptimistinternational.org/women-in-leadership-positions-a-shocking-reality/ "from SoroptimistInternational.org (2020)"),
and continue to be relegated to doing disproportionately more housework, even
when they, not their husband, are their household's sole or primary breadwinner
[@OConnor2019-magazine]? How has the number of women in leadership not kept up
with progress towards equal pay and opportunities for women (though of course
progress here has been too little, too slowly)? How can we promote

One factor contributing to the maintenance of this sort of machismo culture is
that men face penalties for gender norm deviance, such as suggesting a woman for
a promotion, or seeking mentorship from women [@Rosette2015]. For chauvinists, a
man who thinks women are valuable outside of childbearing, child rearing, and
house work is nearly as bad as being a woman. Today hatred in the form of nasty
labels ([especially
"cuck"](https://activisthistory.com/2018/11/19/between-a-cuck-and-a-hard-place-masculinity-and-online-uses-of-the-word-cuck/))
spews from dark recesses of the internet and beyond for men who support women
leaders and believe in the intrinsic and practical value of having both genders
contribute to the well-being of their families, communities, and the world.

In these notes we'll use *evolutionary game theory* to understand what critical
fraction of a population must be *norm inverters* in order to guarantee that
feminism emerges where there are a large prevalence of women leaders and men
followers. In our model, women and men partner together for a "dance" where two
neighboring agents of different genders each do one of two behaviors: *Lead* or
*Follow*. Without a gender norm against men who follow women, the mixed-gender
partners both receive a payoff of 1 as long as one leads and one follows. If
there is a gender norm, this means men who follow women will still receive a
payoff of 1, but then are penalized for it. We represent this penalty for social
deviance by the Greek letter delta, $\delta$.

We hypothesize that there is a critical initial prevalence of norm inverters
(women lead, men follow) at which the system is highly likely to transition from
from machismo (majority/all male leaders) to feminism (majority/all female
leaders). We will calculate this in three stages: first using replicator
dynamics that assumes an infinite population size and a well-mixed population.
Second, with an agent-based social behavior model with a complete network,
essentially a finite, well-mixed population. Finally, we will examine the effect
of some different network structures representing real-world networks, such as
preferential attachment networks, interconnected spatial grids, and small-world
networks.

## Model

### Initialization

-   Complete social network to start
-   Set genders randomly with N/2 of each gender. Note this means agents won't
    have the same number of same- and opposite-gender neighbors as one another.
-   Set the deviance penalty $\delta$ and an initial fraction of women as
    leaders/men as followers, which we call $I$ for gender role *inversion*, to
    see how great initial support for norm inversion must be to reach "feminism"
    outcomes instead of "machismo" outcomes

## Gendered payoff matrices

Payoff matrices are more complicated in gendered division of labor problems
compared to the spatial cooperation problem of the previous chapter. They are
read as follows: the row labels indicate the behavior of the focal agent. If the
focal agent is a woman, her payoff can be read from the matrix by finding her
behavior among the row labels, e.g., *Lead* or *Follow* in the Partner Dance
game, then finding her man partner's behavior among the column labels. Use these
two behaviors to find the payoff matrix cell inside the border in the bottom
right corner of the payoff matrix (Table 1).

### Partner dance

-   If there is no social sanction for men this means there is no deviance
    penalty, i.e., $\delta = 0$. When $\delta \geq 0$, then men suffer some
    judgement for choosing to follow a woman.

#### Payoff matrix

{{< include tables/malefollow-sanction.html >}}

### Computational experiment

-   Our primary explanatory variable is the initial prevalence of gender role
    *inverters*, call it $I\in[0, 1]$ for which we will test values from 0.1 to
    0.9 in steps of 0.2 to start. We observe the prevalence of women leaders
    over time and the prevalence at $t=50$ of women leaders or success rate of
    achieving fixation of women leaders.

## Analysis

### Replicator dynamic

![Machismo basin of attraction (blue arrows) grows with deviance penalty, while
the Feminist basin of attraction shrinks (pink
arrows).](images/clipboard-3974033933.png){#fig-replicator
alt="Machismo basin of attraction (blue arrows) grows with deviance penalty, while the Feminist basin of attraction shrinks (pink arrows)."
width="1500"}

### Complete network

### Other networks

## Discussion
